// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crznqnxuggylhxdoazxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyem5xbnh1Z2d5bGh4ZG9henh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTc2NjEsImV4cCI6MjA2Nzc5MzY2MX0.0veX9x_-A72QloPZSgkaqzvH6xBR93NH0LXueYFfeKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});